name: build
on: 
  push:
  workflow_dispatch:

jobs:
  build:
    name: Build Test

    strategy:
      matrix:
        include:
          - os: ios
            output: ./app-ios.tar.gz
          - os: android
            output: ./app-android.apk

    runs-on: ubuntu-latest

    steps:
      - name: Check for EXPO_TOKEN
        run: |
          if [ -z "${{ secrets.EXPO_TOKEN }}" ]; then
            echo "You must provide an EXPO_TOKEN secret linked to this project's Expo account in this repo's secrets. Learn more: https://docs.expo.dev/eas-update/github-actions"
            exit 1
          fi

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 20.x
          cache: npm

      - name: Install Dependencies
        run: npm install --legacy-peer-deps

      - name: Setup EAS
        uses: expo/expo-github-action@v8
        with:
          expo-version: latest
          eas-version: latest
          eas-cache: true
          expo-cache: true
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Build
        run: eas build --non-interactive --platform ${{ matrix.os }} --profile development --local --output=${{ matrix.output }}
      
      - name: Upload binary
        uses: actions/upload-artifact@v3
        with:
          name: app-${{ matrix.os }}
          path: ${{ matrix.output }}