name: build-ios
on: 
  push:
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ios
            output: ./app-ios.tar.gz
            runs-on: macos-latest

    name: Build for ${{ matrix.os }}

    runs-on: ${{ matrix.runs-on }}

    steps:
      - name: Check for EXPO_TOKEN
        run: |
          if [ -z "${{ secrets.EXPO_TOKEN }}" ]; then
            echo "You must provide an EXPO_TOKEN secret linked to this project's Expo account in this repo's secrets. Learn more: https://docs.expo.dev/eas-update/github-actions"
            exit 1
          fi

      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v2
        with:
          version: latest

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: pnpm

      - name: Install Dependencies
        run: pnpm install

      - name: Cache cocoapods
        if: ${{ matrix.os == 'ios' }}
        uses: actions/cache@v4
        with:
          path: /ios/Pods
          key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pods-

      - name: Setup EAS
        uses: expo/expo-github-action@v8
        with:
          expo-version: latest
          eas-version: latest
          eas-cache: true
          expo-cache: true
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Install Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable

      - name: Build
        run: pnpm run build:${{ matrix.os }}
      
      - name: Upload binary
        uses: actions/upload-artifact@v4
        with:
          name: app-${{ matrix.os }}
          path: ${{ matrix.output }}