name: build-android
on: 
  push:
  workflow_dispatch:

jobs:
  build:
    name: Build Test
    runs-on: ubuntu-latest
    env:
      GRADLE_OPTS: -Dorg.gradle.jvmargs=-Xmx3072m -XX:MaxMetaspaceSize=1024m

    steps:
      - name: Check for EXPO_TOKEN
        run: |
          if [ -z "${{ secrets.EXPO_TOKEN }}" ]; then
            echo "You must provide an EXPO_TOKEN secret linked to this project's Expo account in this repo's secrets. Learn more: https://docs.expo.dev/eas-update/github-actions"
            exit 1
          fi

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 20.x
          cache: npm

      - name: Install Dependencies
        run: npm install --legacy-peer-deps

      - name: Setup EAS
        uses: expo/expo-github-action@v8
        with:
          expo-version: latest
          eas-version: latest
          eas-cache: true
          expo-cache: true
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Build
        run: eas build --non-interactive --platform android --profile production --local --output=./app-android.apk
      
      - name: Upload binary
        uses: actions/upload-artifact@v3
        with:
          name: app-android
          path: app-android.apk